allowBuilds:
  '@datadog/native-appsec': true
  '@datadog/native-iast-taint-tracking': true
  '@datadog/native-metrics': true
  '@datadog/pprof': true
  '@sentry/cli': true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
